/**
 * Automatically translated from Java to Java
 * 
 * Original file: src/main/java/com/example/library/Book.java
 * Module: Book
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.ssbt.ipp.model;

public class Book {
    private String isbn;
    private String title;
    private String author;
    private Integer publicationYear;
    private Boolean isAvailable;
    
    public Book(String isbn, String title, String author, Integer year) {
        this.isbn = isbn;
        this.title = title;
        this.author = author;
        this.publicationYear = year;
        this.isAvailable = true;
    }
    
    public String getIsbn() { return isbn; }
    public String getTitle() { return title; }
    public String getAuthor() { return author; }
    public Integer getPublicationYear() { return publicationYear; }
    public Boolean isAvailable() { return isAvailable; }
    
    public void setAvailable(Boolean available) {
        this.isAvailable = available;
    }
    
    public void displayInfo() {
        System.out.println("ISBN: " + isbn);
        System.out.println("Title: " + title);
        System.out.println("Author: " + author);
        System.out.println("Year: " + publicationYear);
        System.out.println("Available: " + (isAvailable ? "Yes" : "No"));
    }
}